baseURL = "/"
languageCode = "en-us"
title = "But Why?"
theme = "beautifulhugo"

DefaultContentLanguage = "en"

[pagination]
  pagerSize = 10

[Params]
  subtitle = "Short web explainers and back-of-envelope analyses."
  mainSections = ["posts"]
  dateFormat = ":date_long"
  rss = true
  readingTime = false
  wordCount = false
  colorScheme = "auto"
  socialShare = false
  delayDisqus = true
  showRelatedPosts = false
  headerImgStyle = "narrow"

[markup.highlight]
  noClasses = false

[markup.goldmark.parser.attribute]
  block = true

[markup.goldmark.renderer]
  unsafe = true

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1
